version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    networks:
      - curramba_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_VOLUME_CONF}nginx.conf:/etc/nginx/nginx.conf:rw
      - ${NGINX_VOLUME_CONF}:/usr/local/conf.d:rw
      - ${NGINX_VOLUME_TLS}:/usr/local/tls:rw
    restart: on-failure

networks:
  curramba_network:
    external: true