version: '3.8'

services:
  app-sample-1:
    image: nginx:latest
    container_name: app-sample-1
    networks:
      - curramba_network
    volumes:
      - ./nginx/:/usr/share/nginx/html:rw
      - ./conf.d/:/etc/nginx/conf.d:rw
    expose:
      - "80"

networks:
  curramba_network:
    external: true